import './globals.css';
import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import ApolloProvider from '../components/ApolloProvider';

const nunito = Nunito({ subsets: ['latin'], weight: ['400', '700'] });

export const metadata: Metadata = {
  title: 'My Next.js App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={nunito.className}>
      <body className={nunito.className}>
        <ApolloProvider>{children}</ApolloProvider>
      </body>
    </html>
  );
}
